spring:
  cloud:
    gateway:
      routes:
      - id: community-shop
        uri: http://localhost:8081
        predicates:
        - Path=/api/shop/**
        filters:
        - RewritePath=/api/(?<path>.*), /$\{path}
      - id: community-user
        uri: http://localhost:8082
        predicates:
        - Path=/api/user/**
        filters:
        - RewritePath=/api/(?<path>.*), /$\{path}